name: Deploy CDK Stack

#on:
#  push:
    #branches: [ main ]
    #paths-ignore:
    #  - 'src/file_converter_ecr_image/**' 
    #  - '.github/workflows/**'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG : ${{ github.sha }} # No necesario ya que no se construye imagen pero se agrega para mantener consistencia

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install CDK and dependencies
        run: |
          pip install -r infra/requirements.txt
          npm install -g aws-cdk

      - name: Get list of stacks
        working-directory: infra
        id: stacks
        run: |
          STACKS=$(cdk list | grep -v CW357221ParametrosDevOps-LambdaEcrS3TriggerStack | tr '\n' ' ')
          echo "stacks=$STACKS" >> $GITHUB_OUTPUT
        env:
          DB_HOST: ${{ secrets.LAMBDA_DB_HOST }}
          DB_USER: ${{ secrets.LAMBDA_DB_USER }}
          DB_PASSWORD: ${{ secrets.LAMBDA_DB_PASSWORD }}
          ARCGIS_CLIENT_ID : ${{secrets.ARCGIS_CLIENT_ID}}
          ARCGIS_CLIENT_SECRET : ${{secrets.ARCGIS_CLIENT_SECRET}}  
          GRAFANA_API_ACCESS : ${{secrets.GRAFANA_API_ACCESS}}   
          IMAGE_TAG: ${{ env.IMAGE_TAG }}          
          GMAIL_EMAIL_PASSWORD : ${{secrets.GMAIL_EMAIL_PASSWORD}}


      - name: Synthesize CDK
        working-directory: infra
        run: cdk synth ${{ steps.stacks.outputs.stacks }}
        env:
          DB_HOST: ${{ secrets.LAMBDA_DB_HOST }}
          DB_USER: ${{ secrets.LAMBDA_DB_USER }}
          DB_PASSWORD: ${{ secrets.LAMBDA_DB_PASSWORD }}
          ARCGIS_CLIENT_ID : ${{secrets.ARCGIS_CLIENT_ID}}
          ARCGIS_CLIENT_SECRET : ${{secrets.ARCGIS_CLIENT_SECRET}}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          GRAFANA_API_ACCESS : ${{secrets.GRAFANA_API_ACCESS}}
          GMAIL_EMAIL_PASSWORD : ${{secrets.GMAIL_EMAIL_PASSWORD}}

      - name: Deploy CDK stack
        working-directory: infra
        run: cdk deploy ${{ steps.stacks.outputs.stacks }} --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-west-2"
          DB_HOST: ${{ secrets.LAMBDA_DB_HOST }}
          DB_USER: ${{ secrets.LAMBDA_DB_USER }}
          DB_PASSWORD: ${{ secrets.LAMBDA_DB_PASSWORD }}
          ARCGIS_CLIENT_ID : ${{secrets.ARCGIS_CLIENT_ID}}
          ARCGIS_CLIENT_SECRET : ${{secrets.ARCGIS_CLIENT_SECRET}}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          GRAFANA_API_ACCESS : ${{secrets.GRAFANA_API_ACCESS}}
          GMAIL_EMAIL_PASSWORD : ${{secrets.GMAIL_EMAIL_PASSWORD}}